version: "2"
services:
  node:
    image: "singletron/desafio_concrete:production"
    restart: always
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    expose:
      - "8081"
    ports:
      - "8081:8081"
    command: "npm start"
    depends_on:
    - mongo
    links:
    - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
